{% set name = "actions-includes" %}
{% set version = "0.0.post150" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1b92d7b693d789ecd2857fe33710ac8c16e265fc20302bab87a73075ab476833

build:
  number: 0
  noarch: python
  entry_points:
    - actions_include=actions_includes:main
    - actions_include_check=actions_includes.check:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >={{ python_min }}
    - ruamel.yaml

test:
  imports:
    - actions_includes
  commands:
    - pip check
    - actions_include --help
    - actions_include_check --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mithro/actions-includes
  summary: Tool for flattening include statements in GitHub actions workflow.yml files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
