{% set name = "actions-includes" %}
{% set version = "0.0.post140" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/actions-includes-{{ version }}.tar.gz
  sha256: ae286cc068da436b8eccd6dd1f8a1ec9849533fa14cdb54a87f5212adde9e023

build:
  number: 0
  noarch: python
  entry_points:
    - actions_include=actions_includes:main
    - actions_include_check=actions_includes.check:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.8
    - ruamel.yaml

test:
  imports:
    - actions_includes
  commands:
    - pip check
    - actions_include --help
    - actions_include_check --help
  requires:
    - pip

about:
  home: https://github.com/mithro/actions-includes
  summary: Tool for flattening include statements in GitHub actions workflow.yml files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
